import type { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Header from "../components/nav/navbar";
import { Providers } from "./provider";
import "aos/dist/aos.css";
import Aosanimation from "../components/animation/aos";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meeting Room",
  description: "Generated by Meeting Room",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <NextUIProvider>
            <Header />
            <Aosanimation>{children}</Aosanimation>
          </NextUIProvider>
        </Providers>
      </body>
    </html>
  );
}
